/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Hecate */

#ifndef _Included_org_Hecate
#define _Included_org_Hecate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Hecate
 * Method:    inject_mfrank_jni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Hecate_inject_1mfrank_1jni
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_Hecate
 * Method:    remove_mfrank_jni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Hecate_remove_1mfrank_1jni
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
